# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0010_add_reserved_code_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='treestyle',
        ),
    ]
