# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-17 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0011_remove_project_treestyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ignoredfiles',
        ),
    ]
