# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0002_store_translation_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='file_mtime',
            new_name='old_file_mtime',
        ),
    ]
