# Generated by Django 2.2.9 on 2020-01-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0004_add_file_mtime_integer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'base_manager_name': 'objects', 'ordering': ['pootle_path']},
        ),
    ]
