# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0016_blank_last_sync_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='priority',
        ),
    ]
