# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0017_remove_unit_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_template',
        ),
    ]
