# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0018_remove_store_is_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='filetype',
        ),
    ]
