# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_allow_null_last_login"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="unit_rows",),
    ]
