# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pootle", "0002_duedate_path_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="duedate",
            index=models.Index(
                fields=["due_on", "pootle_path", "modified_by"],
                name="pootle_dued_due_on_ee8c5e_idx",
            ),
        ),
    ]
